[package]
name = "core"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
tracing = "0.1.41"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0"

# Add MongoDB dependencies
mongodb = "3.2"

# Workspace Projects
shared = { path = "../shared"}
